version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "${PGPORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  tamakkon_bot:
    build:
      context: .
    image: tamakkon_bot:latest
    depends_on:
      - db
    restart: always

volumes:
  pgdata: